// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BarClient is an autogenerated mock type for the BarClient type
type BarClient struct {
	mock.Mock
}
