// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FooRepository is an autogenerated mock type for the FooRepository type
type FooRepository struct {
	mock.Mock
}
