// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	api "github.com/aeramu/example/service/api"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Bar provides a mock function with given fields: ctx, req
func (_m *Service) Bar(ctx context.Context, req api.BarReq) (*api.BarRes, error) {
	ret := _m.Called(ctx, req)

	var r0 *api.BarRes
	if rf, ok := ret.Get(0).(func(context.Context, api.BarReq) *api.BarRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.BarRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, api.BarReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Foo provides a mock function with given fields: ctx, req
func (_m *Service) Foo(ctx context.Context, req api.FooReq) (*api.FooRes, error) {
	ret := _m.Called(ctx, req)

	var r0 *api.FooRes
	if rf, ok := ret.Get(0).(func(context.Context, api.FooReq) *api.FooRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.FooRes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, api.FooReq) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
